todo_index:
  path: api/todos
  controller: App\Controller\TodoController:index
  methods: [GET]

todo_create:
  path: api/create/todo
  controller: App\Controller\TodoController:store
  methods: [POST]

todo_children_create:
  path: api/create/children/todo
  controller: App\Controller\TodoController:storeChildren
  methods: [POST]

todo_delete:
  path: api/delete/todo/{todo}
  controller: App\Controller\TodoController:delete
  methods: [DELETE]

todo_update:
  path: api/update/todo/{todo}
  controller: App\Controller\TodoController:update
  methods: [PATCH]

#user_show:
#  path: api/show/user/{id}
#  controller: App\Controller\UserController:show
#  methods: [GET]
#  requirements:
#    id: '\d+'

