todo_index:
  path: api/todos
  controller: App\Controller\TodoController:index
  methods: [GET]

todo_create:
  path: api/create/todo
  controller: App\Controller\TodoController:store
  methods: [POST]

todo_update:
  path: api/update/todo/{todo}
  controller: App\Controller\TodoController:update
  methods: [PATCH]

search_todo:
  path: api/search/todos
  controller: App\Controller\TodoController:search
  methods: [GET]

delete_todo:
  path: api/delete/todo/{todo}
  controller: App\Controller\TodoController:delete
  methods: [DELETE]


todo_children_create:
  path: api/create/children/todo
  controller: App\Controller\TodoChildrenController:store
  methods: [POST]


todo_children_delete:
  path: api/delete/children/todo/{todo}
  controller: App\Controller\TodoChildrenController:delete
  methods: [DELETE]
